name: build-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Print Current Path
        run: pwd
      - name: Build, Test and Coverage
        run: fastlane build_and_test
